### PR TITLE
try to use PR

### PR DESCRIPTION
**Pull request by wang-kai-xuan**
- just modidy git repo ignore rules

### CODE REVIEW

**Comment by iroan** [comment]
- heihei, i will close your pr.
- try again later, i will accept it.

**Comment by iroan** [comment]
now

**Comment by wang-kai-xuan** [comment]
wait a moment!

**Comment by iroan** [comment]
closed

**Comment by iroan** [comment]
reopen

**Comment by iroan** [comment]
close again

**Comment by iroan** [comment]
嘿嘿

**Comment by iroan** [comment]
test

**Pull request merged**
